import mongoose from 'mongoose'

const upload = new mongoose.Schema({
  id:                   { type: String },
  created:              { type: Date },
  timestamp:            { type: Date },
  name:                 { type: String },
  title:                { type: String },
  mimetype:             { type: String },
  filetype:             { type: String },
  pretty_type:          { type: String },
  user:                 { type: String },
  editable:             { type: Boolean },
  size:                 { type: Number },
  mode:                 { type: String },
  is_external:          { type: Boolean },
  external_type:        { type: String },
  is_public:            { type: Boolean },
  public_url_shared:    { type: Boolean },
  display_as_bot:       { type: Boolean },
  username:             { type: String },
  url_private:          { type: String },
  url_private_download: { type: String },
  thumb_64:             { type: String },
  thumb_80:             { type: String },
  thumb_360:            { type: String },
  thumb_360_w:          { type: Number },
  thumb_360_h:          { type: Number },
  thumb_480:            { type: String },
  thumb_480_w:          { type: Number },
  thumb_480_h:          { type: Number },
  thumb_160:            { type: String },
  thumb_720:            { type: String },
  thumb_720_w:          { type: Number },
  thumb_720_h:          { type: Number },
  thumb_960:            { type: String },
  thumb_960_w:          { type: Number },
  thumb_960_h:          { type: Number },
  image_exif_rotation:  { type: Number },
  original_w:           { type: Number },
  original_h:           { type: Number },
  permalink:            { type: String },
  permalink_public:     { type: String }
})

export default mongoose.model('Upload', upload)